// Anglican Churches of Jamaica - Final Corrected Dataset
const churches = [
    {"Name":"All Saints","Location":"Crofts Hill","Parish":"Clarendon","Longitude":-77.20749,"Latitude":18.1361,"Status":"Active","Classification":"Church"},
    {"Name":"All Saints'","Location":"Richmond Park","Parish":"Clarendon","Longitude":-77.29,"Latitude":17.97,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"Holy Trinity","Location":"Park Hall","Parish":"Clarendon","Longitude":-77.24,"Latitude":18.15,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Augustine's Church","Location":"Porous","Parish":"Clarendon","Longitude":-77.23,"Latitude":17.97,"Status":"Active","Classification":"Church"},
    {"Name":"St. Bartholomew's","Location":"Frankfield","Parish":"Clarendon","Longitude":-77.39,"Latitude":18.17,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Benedict's Mission","Location":"Milk River","Parish":"Clarendon","Longitude":-77.35,"Latitude":17.87,"Status":"Active","Classification":"Mission Station"},
    {"Name":"St. Gabriel's","Location":"May Pen","Parish":"Clarendon","Longitude":-77.24,"Latitude":17.97,"Status":"Active","Classification":"Parish Church (Church)"},
    {"Name":"St. Gregory's","Location":"Red Hills (Clarendon)","Parish":"Clarendon","Longitude":-77.21,"Latitude":18.04,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. James'","Location":"Hayes","Parish":"Clarendon","Longitude":-77.3,"Latitude":17.9,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. John's","Location":"Palmers Cross","Parish":"Clarendon","Longitude":-77.2,"Latitude":17.93,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. John's Church","Location":"Frankfield","Parish":"Clarendon","Longitude":-77.14,"Latitude":18.08,"Status":"Active","Classification":"Church"},
    {"Name":"St. Luke's","Location":"Sanguinetti","Parish":"Clarendon","Longitude":-77.43,"Latitude":18.2,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Luke's Church","Location":"Chapelton","Parish":"Clarendon","Longitude":-77.24,"Latitude":17.96,"Status":"Active","Classification":"Church"},
    {"Name":"St. Mark's","Location":"Beckford Kraal","Parish":"Clarendon","Longitude":-77.32,"Latitude":18.05,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Mary's Church","Location":"Kellits","Parish":"Clarendon","Longitude":-77.26,"Latitude":18.16,"Status":"Active","Classification":"Church"},
    {"Name":"St. Matthew's","Location":"Aenon Town","Parish":"Clarendon","Longitude":-77.37,"Latitude":18.17,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Paul's","Location":"Mocho","Parish":"Clarendon","Longitude":-77.38,"Latitude":18.02,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Paul's Church","Location":"May Pen","Parish":"Clarendon","Longitude":-77.25,"Latitude":17.96,"Status":"Active","Classification":"Church"},
    {"Name":"St. Peter's","Location":"Alley","Parish":"Clarendon","Longitude":-77.28,"Latitude":17.85,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Peter's Church","Location":"Alley","Parish":"Clarendon","Longitude":-77.24,"Latitude":17.96,"Status":"Active","Classification":"Church"},
    {"Name":"St. Saviour's","Location":"Milk River","Parish":"Clarendon","Longitude":-77.33488,"Latitude":17.8782,"Status":"Closed","Classification":"Chapel / Church"},
    {"Name":"St. Stephen's Church","Location":"Rock River","Parish":"Clarendon","Longitude":-77.18,"Latitude":18.08,"Status":"Active","Classification":"Church"},
    {"Name":"St. Thomas'","Location":"Race Course","Parish":"Clarendon","Longitude":-77.26,"Latitude":17.87,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"Hanover Parish Church","Location":"Lucea","Parish":"Hanover","Longitude":-78.17051,"Latitude":18.44964,"Status":"Active","Classification":"Parish Church (Church)"},
    {"Name":"St. Mark's","Location":"Hopewell","Parish":"Hanover","Longitude":-78.03,"Latitude":18.44,"Status":"Ruin?","Classification":"Chapel / Church"},
    {"Name":"Allman Town","Location":"Allman Town","Parish":"Kingston","Longitude":-76.78,"Latitude":17.98,"Status":"Unknown","Classification":"Church"},
    {"Name":"Kingston Parish Church (St. Thomas the Apostle)","Location":"Kingston (Parade/King St)","Parish":"Kingston","Longitude":-76.79,"Latitude":17.97,"Status":"Active","Classification":"Church"},
    {"Name":"St. Alban's","Location":"Kingston","Parish":"Kingston","Longitude":-76.79,"Latitude":17.97,"Status":"Unknown","Classification":"Mission Station"},
    {"Name":"St. George's Church","Location":"1 West Street","Parish":"Kingston","Longitude":-76.79,"Latitude":17.98,"Status":"Active","Classification":"Parish Church"},
    {"Name":"St. Michael's","Location":"Kingston (Allman Town)","Parish":"Kingston","Longitude":-76.78,"Latitude":17.97,"Status":"Unknown","Classification":"Church"},
    {"Name":"St. Michael's Church","Location":"Hannah Town","Parish":"Kingston","Longitude":-76.8,"Latitude":17.98,"Status":"Active","Classification":"Church"},
    {"Name":"St. Peter's Church (Old)","Location":"Port Royal","Parish":"Kingston","Longitude":-76.84,"Latitude":17.94,"Status":"Ruin","Classification":"Church"},
    {"Name":"West Branch","Location":"Kingston","Parish":"Kingston","Longitude":-76.79,"Latitude":17.97,"Status":"Unknown","Classification":"Mission Station"},
    {"Name":"Christ Church","Location":"Christiana","Parish":"Manchester","Longitude":-77.53,"Latitude":18.17,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Augustine's","Location":"Porus","Parish":"Manchester","Longitude":-77.41,"Latitude":17.99,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Barnabas'","Location":"Mile Gully","Parish":"Manchester","Longitude":-77.62,"Latitude":18.12,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. David's","Location":"Snowdon","Parish":"Manchester","Longitude":-77.49,"Latitude":18.08,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Gabriel's Church","Location":"Christiana","Parish":"Manchester","Longitude":-77.49,"Latitude":18.18,"Status":"Active","Classification":"Church"},
    {"Name":"St. George's Church Ruins","Location":"Auchtembeddie","Parish":"Manchester","Longitude":-76.37,"Latitude":18.04,"Status":"Ruin","Classification":"Church"},
    {"Name":"St. James'","Location":"Kendal","Parish":"Manchester","Longitude":-77.55,"Latitude":17.97,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. John the Baptist's","Location":"Coleyville","Parish":"Manchester","Longitude":-77.56,"Latitude":18.16,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Jude's","Location":"Pratville","Parish":"Manchester","Longitude":-77.45,"Latitude":18.06,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Lawrence's","Location":"Devon","Parish":"Manchester","Longitude":-77.59,"Latitude":18.13,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Mark's (Parish Church)","Location":"Mandeville","Parish":"Manchester","Longitude":-77.51,"Latitude":18.04,"Status":"Active","Classification":"Parish Church (Church)"},
    {"Name":"St. Mark's Church","Location":"Williamsfield","Parish":"Manchester","Longitude":-77.47,"Latitude":18.07,"Status":"Active","Classification":"Church"},
    {"Name":"St. Matthew's Church","Location":"Alligator Pond","Parish":"Manchester","Longitude":-77.56,"Latitude":17.87,"Status":"Active","Classification":"Church"},
    {"Name":"St. Michael and All Angels","Location":"New Forest","Parish":"Manchester","Longitude":-77.56629,"Latitude":17.90598,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Patrick's","Location":"Providence","Parish":"Manchester","Longitude":-77.58,"Latitude":18.07,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Paul's","Location":"Spalding","Parish":"Manchester","Longitude":-77.55,"Latitude":18.19,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Paul's Church","Location":"Mile Gully","Parish":"Manchester","Longitude":-77.57,"Latitude":18.17,"Status":"Active","Classification":"Church"},
    {"Name":"St. Philip's","Location":"Old England","Parish":"Manchester","Longitude":-77.57,"Latitude":18.01,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Simon's","Location":"Comfort Hall","Parish":"Manchester","Longitude":-77.46,"Latitude":18.08,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"All Saints'","Location":"Fellowship","Parish":"Portland","Longitude":-76.42,"Latitude":18.02,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"Birnam Wood","Location":"Birnam Wood","Parish":"Portland","Longitude":-76.53,"Latitude":18.05,"Status":"Unknown","Classification":"Church"},
    {"Name":"Boston","Location":"Boston","Parish":"Portland","Longitude":-76.33683,"Latitude":18.13316,"Status":"Unknown","Classification":"Church"},
    {"Name":"Boundbrook Chapel-of-Ease","Location":"Boundbrook","Parish":"Portland","Longitude":-76.46,"Latitude":18.18,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"Buff Bay","Location":"Buff Bay","Parish":"Portland","Longitude":-76.66,"Latitude":18.23,"Status":"Unknown","Classification":"Church"},
    {"Name":"Bybrook","Location":"Bybrook","Parish":"Portland","Longitude":-76.57,"Latitude":18.14,"Status":"Unknown","Classification":"Mission Station"},
    {"Name":"Christ Church (Parish Church)","Location":"Port Antonio","Parish":"Portland","Longitude":-76.46,"Latitude":18.18,"Status":"Active","Classification":"Parish Church (Church)"},
    {"Name":"Claverty Cottage","Location":"Claverty Cottage","Parish":"Portland","Longitude":-76.54,"Latitude":18.13,"Status":"Unknown","Classification":"Mission Station"},
    {"Name":"Cooper's Hill","Location":"Cooper's Hill","Parish":"Portland","Longitude":-76.6,"Latitude":18.11,"Status":"Unknown","Classification":"Mission Station"},
    {"Name":"Fairfield","Location":"Fairfield","Parish":"Portland","Longitude":-76.58,"Latitude":18.06,"Status":"Unknown","Classification":"Mission Station"},
    {"Name":"Hope Bay","Location":"Hope Bay","Parish":"Portland","Longitude":-76.56736,"Latitude":18.20064,"Status":"Unknown","Classification":"Church"},
    {"Name":"John's Hall","Location":"John's Hall","Parish":"Portland","Longitude":-76.6,"Latitude":18.17,"Status":"Unknown","Classification":"Mission Station"},
    {"Name":"Moore Town","Location":"Moore Town","Parish":"Portland","Longitude":-76.45,"Latitude":18.07,"Status":"Unknown","Classification":"Mission Station"},
    {"Name":"Port Antonio","Location":"Port Antonio","Parish":"Portland","Longitude":-76.45,"Latitude":18.18,"Status":"Unknown","Classification":"Church"},
    {"Name":"Rural Hill","Location":"Rural Hill","Parish":"Portland","Longitude":-76.32,"Latitude":18.06,"Status":"Unknown","Classification":"Church"},
    {"Name":"St. Christopher's","Location":"Sherwood Forest","Parish":"Portland","Longitude":-76.33,"Latitude":18.13,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Dunstan's","Location":"Orange Bay","Parish":"Portland","Longitude":-76.53,"Latitude":18.07,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. George's","Location":"Buff Bay","Parish":"Portland","Longitude":-76.66,"Latitude":18.19,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. James'","Location":"Birnamwood","Parish":"Portland","Longitude":-76.7,"Latitude":18.17,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. John's","Location":"Windsor Forest","Parish":"Portland","Longitude":-76.52,"Latitude":18.14,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Joseph's","Location":"Belvedere","Parish":"Portland","Longitude":-76.47,"Latitude":18.18,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Jude's","Location":"Bourbon","Parish":"Portland","Longitude":-76.6,"Latitude":18.18,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Luke's","Location":"Comfort Castle","Parish":"Portland","Longitude":-76.4,"Latitude":18.05,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Margaret's Bay","Location":"St. Margaret's Bay","Parish":"Portland","Longitude":-76.54,"Latitude":18.19,"Status":"Unknown","Classification":"Church"},
    {"Name":"St. Mark's","Location":"Boston","Parish":"Portland","Longitude":-76.35612,"Latitude":18.1629,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Mary's","Location":"Rural Hill","Parish":"Portland","Longitude":-76.45,"Latitude":18.07,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Matthew's","Location":"Mount Herman","Parish":"Portland","Longitude":-76.68,"Latitude":18.1,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Michael's","Location":"Fruitful Vale","Parish":"Portland","Longitude":-76.45,"Latitude":18.07,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Paul's","Location":"Moore Town","Parish":"Portland","Longitude":-76.45,"Latitude":18.02,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Peter's Chapel (Ruin)","Location":"Nonsuch","Parish":"Portland","Longitude":-76.37788,"Latitude":18.14692,"Status":"Ruin","Classification":"Chapel"},
    {"Name":"St. Philip's","Location":"Bangor Ridge","Parish":"Portland","Longitude":-76.57,"Latitude":18.18,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Stephen's Church","Location":"Port Antonio","Parish":"Portland","Longitude":-76.45,"Latitude":18.14,"Status":"Active","Classification":"Church"},
    {"Name":"St. Thomas'","Location":"Manchioneal","Parish":"Portland","Longitude":-76.27999,"Latitude":18.03624,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"August Town","Location":"August Town","Parish":"St. Andrew","Longitude":-76.74,"Latitude":18,"Status":"Unknown","Classification":"Mission Station"},
    {"Name":"Brandon Hill","Location":"Brandon Hill","Parish":"St. Andrew","Longitude":-76.82,"Latitude":18.01,"Status":"Unknown","Classification":"Church"},
    {"Name":"Church of Ascension","Location":"Mona","Parish":"St. Andrew","Longitude":-76.74,"Latitude":18.01,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"Church of the Good Shepherd","Location":"Constant Spring","Parish":"St. Andrew","Longitude":-76.8,"Latitude":18.04,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"Church of the Resurrection","Location":"Duhaney Park","Parish":"St. Andrew","Longitude":-76.84,"Latitude":17.99,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"Church of the Transfiguration","Location":"Havendale","Parish":"St. Andrew","Longitude":-76.82,"Latitude":18.03,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"Clifton","Location":"Clifton","Parish":"St. Andrew","Longitude":-76.77,"Latitude":18.03,"Status":"Unknown","Classification":"Church"},
    {"Name":"Craigton","Location":"Craigton","Parish":"St. Andrew","Longitude":-76.77,"Latitude":18.07,"Status":"Unknown","Classification":"Church"},
    {"Name":"Hunt's Bay","Location":"Hunt's Bay","Parish":"St. Andrew","Longitude":-76.85,"Latitude":17.99,"Status":"Unknown","Classification":"Mission Station"},
    {"Name":"Mavis Bank","Location":"Mavis Bank","Parish":"St. Andrew","Longitude":-76.67,"Latitude":18.02,"Status":"Unknown","Classification":"Church"},
    {"Name":"Mount James","Location":"Mount James","Parish":"St. Andrew","Longitude":-76.79,"Latitude":18.12,"Status":"Unknown","Classification":"Church"},
    {"Name":"St. Andrew (Parish Church)","Location":"Half Way Tree","Parish":"St. Andrew","Longitude":-76.78,"Latitude":18.02,"Status":"Active","Classification":"Parish Church (Church)"},
    {"Name":"St. Andrew Parish Church","Location":"Half-Way-Tree","Parish":"St. Andrew","Longitude":-76.78,"Latitude":18,"Status":"Active","Classification":"Parish Church"},
    {"Name":"St. Augustine's Church","Location":"August Town","Parish":"St. Andrew","Longitude":-76.74,"Latitude":18.04,"Status":"Active","Classification":"Church"},
    {"Name":"St. Barnabas","Location":"Kencot","Parish":"St. Andrew","Longitude":-76.8,"Latitude":18.01,"Status":"Unknown","Classification":"Mission Station"},
    {"Name":"St. Bartholomew's","Location":"Tom's River","Parish":"St. Andrew","Longitude":-76.79,"Latitude":18.11,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Christopher's","Location":"Cavaliers","Parish":"St. Andrew","Longitude":-76.85,"Latitude":18.06,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Christopher's Church","Location":"Woodford","Parish":"St. Andrew","Longitude":-76.43,"Latitude":18.04,"Status":"Active","Classification":"Church"},
    {"Name":"St. Clement's","Location":"Kencot","Parish":"St. Andrew","Longitude":-76.81,"Latitude":18,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Clement's Mission","Location":"Kencot","Parish":"St. Andrew","Longitude":-76.8,"Latitude":18.01,"Status":"Active","Classification":"Mission Station"},
    {"Name":"St. Cyprians","Location":"August Town","Parish":"St. Andrew","Longitude":-76.74,"Latitude":18.02,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. James'","Location":"Mount James","Parish":"St. Andrew","Longitude":-76.85,"Latitude":18.08,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. John's","Location":"Merrivale","Parish":"St. Andrew","Longitude":-76.82,"Latitude":18.05,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Joseph's","Location":"The Grove","Parish":"St. Andrew","Longitude":-76.76,"Latitude":18.02,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Jude's","Location":"Stony Hill","Parish":"St. Andrew","Longitude":-76.83,"Latitude":18.08,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Luke's","Location":"Cross Roads","Parish":"St. Andrew","Longitude":-76.79,"Latitude":18,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Luke's Church","Location":"Cross Roads","Parish":"St. Andrew","Longitude":-76.79,"Latitude":18.01,"Status":"Active","Classification":"Church"},
    {"Name":"St. Margaret's","Location":"Liguanea","Parish":"St. Andrew","Longitude":-76.76,"Latitude":18.02,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Margaret's Church","Location":"Liguanea","Parish":"St. Andrew","Longitude":-76.75,"Latitude":18.02,"Status":"Active","Classification":"Church"},
    {"Name":"St. Margaret's Mission","Location":"Mavis Bank","Parish":"St. Andrew","Longitude":-76.67,"Latitude":18.03,"Status":"Active","Classification":"Mission Station"},
    {"Name":"St. Mark's","Location":"Craigton","Parish":"St. Andrew","Longitude":-76.7,"Latitude":18.07,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Martin's","Location":"Padmore","Parish":"St. Andrew","Longitude":-76.84,"Latitude":18.09,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Martin-in-the-Fields","Location":"Irish Town","Parish":"St. Andrew","Longitude":-76.66,"Latitude":18.08,"Status":"Active","Classification":"Chapel"},
    {"Name":"St. Mary the Virgin","Location":"Maverley","Parish":"St. Andrew","Longitude":-76.83,"Latitude":18,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Mary's","Location":"Woodford","Parish":"St. Andrew","Longitude":-76.71,"Latitude":18.08,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Mary's Chapel","Location":"Lawrencefield","Parish":"St. Andrew","Longitude":-76.75,"Latitude":18.05,"Status":"Active","Classification":"Chapel"},
    {"Name":"St. Matthew's","Location":"Jack's Hill","Parish":"St. Andrew","Longitude":-76.77,"Latitude":18.05,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Michael's","Location":"Mavis Bank","Parish":"St. Andrew","Longitude":-76.68,"Latitude":18.07,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Paul's","Location":"Tower Hill","Parish":"St. Andrew","Longitude":-76.84,"Latitude":18.03,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Peter's","Location":"Clifton","Parish":"St. Andrew","Longitude":-76.8,"Latitude":18.08,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Philip's","Location":"Whitfield Town","Parish":"St. Andrew","Longitude":-76.8,"Latitude":17.98,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Stephen's","Location":"Maryland","Parish":"St. Andrew","Longitude":-76.78,"Latitude":18.12,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Thomas Mission","Location":"Majesty Gardens","Parish":"St. Andrew","Longitude":-76.82,"Latitude":17.99,"Status":"Active","Classification":"Mission / Mission Station"},
    {"Name":"Stony Hill (St. Jude's)","Location":"Stony Hill","Parish":"St. Andrew","Longitude":-76.79,"Latitude":18.09,"Status":"Active","Classification":"Church"},
    {"Name":"Swallowfield","Location":"Swallowfield","Parish":"St. Andrew","Longitude":-76.78,"Latitude":17.99,"Status":"Unknown","Classification":"Mission Station"},
    {"Name":"The Grove","Location":"Constant Spring / The Grove","Parish":"St. Andrew","Longitude":-76.79,"Latitude":18.05,"Status":"Unknown","Classification":"Church"},
    {"Name":"Woodford","Location":"Woodford","Parish":"St. Andrew","Longitude":-76.68,"Latitude":18.04,"Status":"Unknown","Classification":"Church"},
    {"Name":"All Saints Church","Location":"All Saints Road","Parish":"St. Ann","Longitude":-77.1,"Latitude":18.43,"Status":"Active","Classification":"Church"},
    {"Name":"Christ Church","Location":"Moneague","Parish":"St. Ann","Longitude":-77.2,"Latitude":18.17,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Andrew's","Location":"Bamboo","Parish":"St. Ann","Longitude":-77.3,"Latitude":18.36,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Ann Parish Church","Location":"St. Ann's Bay","Parish":"St. Ann","Longitude":-77.2,"Latitude":18.41,"Status":"Active","Classification":"Parish Church (Church)"},
    {"Name":"St. Barnabas'","Location":"Madras","Parish":"St. Ann","Longitude":-77.4,"Latitude":18.33,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. David's","Location":"Brittonville","Parish":"St. Ann","Longitude":-77.28,"Latitude":18.19,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. James'","Location":"Gibraltar","Parish":"St. Ann","Longitude":-77.34,"Latitude":18.34,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. John's","Location":"Ocho Rios","Parish":"St. Ann","Longitude":-77.1,"Latitude":18.41,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. John's Church","Location":"Brown's Town","Parish":"St. Ann","Longitude":-77.35,"Latitude":18.38,"Status":"Active","Classification":"Church"},
    {"Name":"St. John's Mission","Location":"Chalky Hill","Parish":"St. Ann","Longitude":-77.14,"Latitude":18.39,"Status":"Active","Classification":"Mission Station"},
    {"Name":"St. Luke's","Location":"Aboukir","Parish":"St. Ann","Longitude":-77.36,"Latitude":18.34,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Mark's","Location":"Brown's Town","Parish":"St. Ann","Longitude":-77.34,"Latitude":18.32,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Mark's Church","Location":"Main Street","Parish":"St. Ann","Longitude":-77.1,"Latitude":18.41,"Status":"Active","Classification":"Church"},
    {"Name":"St. Mary's Mission","Location":"Aboukir","Parish":"St. Ann","Longitude":-77.18,"Latitude":18.39,"Status":"Active","Classification":"Mission Station"},
    {"Name":"St. Matthew's","Location":"Claremont","Parish":"St. Ann","Longitude":-77.24,"Latitude":18.24,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Paul's Church (Old)","Location":"Pimento Walk","Parish":"St. Ann","Longitude":-77.78,"Latitude":18.05,"Status":"Ruin","Classification":"Church"},
    {"Name":"St. Paul's Mission","Location":"Philadelphia","Parish":"St. Ann","Longitude":-77.25,"Latitude":18.46,"Status":"Active","Classification":"Mission Station"},
    {"Name":"St. Peter's Church","Location":"Queen Street","Parish":"St. Ann","Longitude":-77.11,"Latitude":18.43,"Status":"Active","Classification":"Church"},
    {"Name":"St. Saviour's","Location":"Lime Hall","Parish":"St. Ann","Longitude":-77.17,"Latitude":18.35,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Stephen's Chapel","Location":"Lime Hall","Parish":"St. Ann","Longitude":-77.23,"Latitude":18.42,"Status":"Active","Classification":"Chapel"},
    {"Name":"All Saints'","Location":"Bellas Gate","Parish":"St. Catherine","Longitude":-77.07,"Latitude":18.08,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"Church of the Holy Trinity","Location":"Linstead","Parish":"St. Catherine","Longitude":-77.02,"Latitude":18.12,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"Goba","Location":"Goffe / Goba (district)","Parish":"St. Catherine","Longitude":-77.02,"Latitude":18.1,"Status":"Unknown","Classification":"Mission Station"},
    {"Name":"Harewood","Location":"Harewood","Parish":"St. Catherine","Longitude":-77.09,"Latitude":18.04,"Status":"Unknown","Classification":"Church"},
    {"Name":"Highgate (St Catherine)","Location":"Highgate (Sligoville area)","Parish":"St. Catherine","Longitude":-76.99,"Latitude":18.12,"Status":"Unknown","Classification":"Church"},
    {"Name":"Linstead","Location":"Linstead","Parish":"St. Catherine","Longitude":-77.03,"Latitude":18.14,"Status":"Unknown","Classification":"Church"},
    {"Name":"Lluidas Vale","Location":"Lluidas Vale","Parish":"St. Catherine","Longitude":-77.18,"Latitude":18.22,"Status":"Unknown","Classification":"Church"},
    {"Name":"Lucky Valley","Location":"Lucky Valley","Parish":"St. Catherine","Longitude":-77.2,"Latitude":18.18,"Status":"Unknown","Classification":"Mission Station"},
    {"Name":"Old Harbour","Location":"Old Harbour","Parish":"St. Catherine","Longitude":-77.11,"Latitude":17.96,"Status":"Unknown","Classification":"Church"},
    {"Name":"Old Harbour Bay","Location":"Old Harbour Bay","Parish":"St. Catherine","Longitude":-77.1,"Latitude":17.92,"Status":"Active","Classification":"Church"},
    {"Name":"Point Hill","Location":"Point Hill","Parish":"St. Catherine","Longitude":-77.11,"Latitude":18.15,"Status":"Unknown","Classification":"Church"},
    {"Name":"SS Simon and Jude","Location":"Ewarton","Parish":"St. Catherine","Longitude":-77.07,"Latitude":18.16,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"Somerset Hall","Location":"Somerset Hall","Parish":"St. Catherine","Longitude":-76.95,"Latitude":18.12,"Status":"Unknown","Classification":"Church"},
    {"Name":"St. Augustine's","Location":"Watermount","Parish":"St. Catherine","Longitude":-77,"Latitude":18.08,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Barnabas'","Location":"Crescent","Parish":"St. Catherine","Longitude":-77.04,"Latitude":18.02,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Boniface","Location":"Mount Industry","Parish":"St. Catherine","Longitude":-76.94,"Latitude":18.09,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Catherine Parish Church","Location":"Spanish Town","Parish":"St. Catherine","Longitude":-76.96,"Latitude":17.99,"Status":"Active","Classification":"Parish Church"},
    {"Name":"St. Dorothy's","Location":"Old Harbour","Parish":"St. Catherine","Longitude":-77.09,"Latitude":17.94,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Dorothy's Church","Location":"Old Harbour","Parish":"St. Catherine","Longitude":-77.11,"Latitude":17.94,"Status":"Active","Classification":"Church"},
    {"Name":"St. Faith's","Location":"Faith's","Parish":"St. Catherine","Longitude":-77.08,"Latitude":18.13,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. George's","Location":"Point Hill","Parish":"St. Catherine","Longitude":-77.07,"Latitude":18.07,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Jago de la Vega (The Cathedral)","Location":"Spanish Town","Parish":"St. Catherine","Longitude":-76.95,"Latitude":18,"Status":"Active","Classification":"Cathedral"},
    {"Name":"St. John's","Location":"Sligoville","Parish":"St. Catherine","Longitude":-76.92,"Latitude":18.08,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. John's Church","Location":"Linstead","Parish":"St. Catherine","Longitude":-77.03,"Latitude":18.14,"Status":"Active","Classification":"Church"},
    {"Name":"St. John's OPC","Location":"Guanaboa Vale","Parish":"St. Catherine","Longitude":-77.03,"Latitude":18.04,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Joseph's","Location":"Innswood/McCook's Pen","Parish":"St. Catherine","Longitude":-76.97,"Latitude":17.94,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Mark's","Location":"Ham Walk","Parish":"St. Catherine","Longitude":-77.05,"Latitude":18.05,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Matthew's","Location":"Mt. Moorland","Parish":"St. Catherine","Longitude":-76.99,"Latitude":18.03,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Peter's","Location":"Old Works","Parish":"St. Catherine","Longitude":-76.97,"Latitude":18.07,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Phillip's","Location":"Morris Hall","Parish":"St. Catherine","Longitude":-77.05,"Latitude":18.08,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Saviour's","Location":"Harewood","Parish":"St. Catherine","Longitude":-77.05,"Latitude":18.09,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Thomas-ye-Vale","Location":"Bog Walk","Parish":"St. Catherine","Longitude":-76.98,"Latitude":18.09,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"Trinity (Spanish Town)","Location":"Spanish Town","Parish":"St. Catherine","Longitude":-76.96,"Latitude":17.99,"Status":"Unknown","Classification":"Church"},
    {"Name":"Woodside (St Catherine)","Location":"Woodside","Parish":"St. Catherine","Longitude":-77.19,"Latitude":18.24,"Status":"Unknown","Classification":"Mission Station"},
    {"Name":"All Souls","Location":"Luana","Parish":"St. Elizabeth","Longitude":-77.87648,"Latitude":18.07036,"Status":"Active","Classification":"Church"},
    {"Name":"All Souls'","Location":"Brompton","Parish":"St. Elizabeth","Longitude":-77.81,"Latitude":18.05,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"Epiphany","Location":"Bigwoods District","Parish":"St. Elizabeth","Longitude":-77.71237,"Latitude":17.9363,"Status":"Active","Classification":"Church"},
    {"Name":"Holy Trinity","Location":"Whitehall","Parish":"St. Elizabeth","Longitude":-77.85451,"Latitude":18.12143,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St Alban's","Location":"Stanmore Hill","Parish":"St. Elizabeth","Longitude":-77.72293,"Latitude":18.00294,"Status":"Active","Classification":"Church"},
    {"Name":"St. Andrew's","Location":"Gilnock","Parish":"St. Elizabeth","Longitude":-77.66437,"Latitude":18.05597,"Status":"Active","Classification":"Church"},
    {"Name":"St. Augustine's","Location":"Mountainside","Parish":"St. Elizabeth","Longitude":-77.68,"Latitude":17.94,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Barnabas'","Location":"Siloah","Parish":"St. Elizabeth","Longitude":-77.62,"Latitude":18.15,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. John's (Parish Church)","Location":"Black River","Parish":"St. Elizabeth","Longitude":-77.85,"Latitude":18.02,"Status":"Active","Classification":"Parish Church (Church)"},
    {"Name":"St. John's Church","Location":"Black River","Parish":"St. Elizabeth","Longitude":-77.85,"Latitude":18.02,"Status":"Active","Classification":"Church"},
    {"Name":"St. Jude's","Location":"Slipe","Parish":"St. Elizabeth","Longitude":-77.8,"Latitude":18.03,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Luke's","Location":"Balaclava","Parish":"St. Elizabeth","Longitude":-77.63,"Latitude":18.15,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Margaret's","Location":"Middle Quarters","Parish":"St. Elizabeth","Longitude":-77.84,"Latitude":18.07,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Mark's","Location":"Southfield","Parish":"St. Elizabeth","Longitude":-77.6663,"Latitude":17.88187,"Status":"Active","Classification":"Church"},
    {"Name":"St. Mark's Church","Location":"Siloah","Parish":"St. Elizabeth","Longitude":-77.70932,"Latitude":18.17315,"Status":"Active","Classification":"Church"},
    {"Name":"St. Martin's","Location":"Accompong","Parish":"St. Elizabeth","Longitude":-77.77735,"Latitude":18.19804,"Status":"Active","Classification":"Mission"},
    {"Name":"St. Mary's Church","Location":"Balaclava","Parish":"St. Elizabeth","Longitude":-77.64,"Latitude":18.17,"Status":"Active","Classification":"Church"},
    {"Name":"St. Matthew's","Location":"Santa Cruz","Parish":"St. Elizabeth","Longitude":-77.69742,"Latitude":18.069,"Status":"Active","Classification":"Church"},
    {"Name":"St. Paul's","Location":"Barbary Hall","Parish":"St. Elizabeth","Longitude":-77.76863,"Latitude":17.96002,"Status":"Active","Classification":"Church"},
    {"Name":"St. Peter's","Location":"Flagaman","Parish":"St. Elizabeth","Longitude":-77.72454,"Latitude":17.89875,"Status":"Active","Classification":"Church"},
    {"Name":"St. Stephen's Church","Location":"Malvern","Parish":"St. Elizabeth","Longitude":-77.7,"Latitude":17.97,"Status":"Active","Classification":"Church"},
    {"Name":"St. Thomas'","Location":"Lacovia","Parish":"St. Elizabeth","Longitude":-77.76808,"Latitude":18.09196,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"Holy Cross","Location":"Mount Salem","Parish":"St. James","Longitude":-77.93,"Latitude":18.44,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"Holy Trinity","Location":"Westgate","Parish":"St. James","Longitude":-77.92,"Latitude":18.44,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"Mary Magdalene","Location":"Granville","Parish":"St. James","Longitude":-77.93,"Latitude":18.4,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Alban's","Location":"Ashton","Parish":"St. James","Longitude":-77.92,"Latitude":18.32,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Bartholomew's","Location":"Berkshire","Parish":"St. James","Longitude":-77.81,"Latitude":18.47,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Francis'","Location":"Glendevon","Parish":"St. James","Longitude":-77.89,"Latitude":18.45,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. James Parish Church","Location":"Sam Sharpe Square","Parish":"St. James","Longitude":-77.92,"Latitude":18.47,"Status":"Active","Classification":"Parish Church"},
    {"Name":"St. James' (Parish Church)","Location":"Montego Bay","Parish":"St. James","Longitude":-77.93,"Latitude":18.47,"Status":"Active","Classification":"Parish Church (Church)"},
    {"Name":"St. John's","Location":"Grace Hill","Parish":"St. James","Longitude":-77.94,"Latitude":18.37,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Leonard's","Location":"Blue Hole","Parish":"St. James","Longitude":-77.93,"Latitude":18.45,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Luke's","Location":"Vaughnsfield","Parish":"St. James","Longitude":-77.82523,"Latitude":18.3527,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Mary's","Location":"Montpelier","Parish":"St. James","Longitude":-77.92,"Latitude":18.36,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Stephen's","Location":"Cornwall Mountain","Parish":"St. James","Longitude":-77.85,"Latitude":18.33,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"Church of the Ephipany","Location":"Richmond","Parish":"St. Mary","Longitude":-76.91,"Latitude":18.2,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"Holy Trinity","Location":"Retreat","Parish":"St. Mary","Longitude":-77.02,"Latitude":18.37,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Agatha's","Location":"Bromley","Parish":"St. Mary","Longitude":-76.88,"Latitude":18.27,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Alban's","Location":"Albion Mountain","Parish":"St. Mary","Longitude":-76.95,"Latitude":18.37,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Andrew's","Location":"Labyrinth","Parish":"St. Mary","Longitude":-76.93,"Latitude":18.3,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Barnabas'","Location":"Enfield","Parish":"St. Mary","Longitude":-76.83,"Latitude":18.25,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Benedict's Church","Location":"Richmond","Parish":"St. Mary","Longitude":-76.89,"Latitude":18.22,"Status":"Active","Classification":"Church"},
    {"Name":"St. Cyprian's","Location":"Highgate","Parish":"St. Mary","Longitude":-76.87,"Latitude":18.23,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Elizabeth's","Location":"Mason Hall","Parish":"St. Mary","Longitude":-77.02,"Latitude":18.23,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Gabriel's","Location":"Woodside","Parish":"St. Mary","Longitude":-76.8,"Latitude":18.22,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. James'","Location":"Annotto Bay","Parish":"St. Mary","Longitude":-76.77,"Latitude":18.26,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. John's","Location":"Gayle","Parish":"St. Mary","Longitude":-77,"Latitude":18.28,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Luke's","Location":"Bonny Gate","Parish":"St. Mary","Longitude":-76.91,"Latitude":18.35,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Luke's Church","Location":"Highgate","Parish":"St. Mary","Longitude":-76.9,"Latitude":18.25,"Status":"Active","Classification":"Church"},
    {"Name":"St. Margaret's","Location":"Clifton Lodge","Parish":"St. Mary","Longitude":-76.92,"Latitude":18.38,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Margaret's Church","Location":"Annotto Bay","Parish":"St. Mary","Longitude":-76.77,"Latitude":18.27,"Status":"Active","Classification":"Church"},
    {"Name":"St. Mark's","Location":"Scott's Hall","Parish":"St. Mary","Longitude":-76.87,"Latitude":18.15,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Mark's Church","Location":"Port Maria","Parish":"St. Mary","Longitude":-76.89,"Latitude":18.37,"Status":"Active","Classification":"Church"},
    {"Name":"St. Martin's","Location":"Martin","Parish":"St. Mary","Longitude":-76.99,"Latitude":18.26,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Mary (Parish Church)","Location":"Port Maria","Parish":"St. Mary","Longitude":-76.88,"Latitude":18.38,"Status":"Active","Classification":"Parish Church (Church)"},
    {"Name":"St. Mary's Church","Location":"Gayle","Parish":"St. Mary","Longitude":-76.99,"Latitude":18.32,"Status":"Active","Classification":"Church"},
    {"Name":"St. Mary's Church (Old)","Location":"Rio Nuevo","Parish":"St. Mary","Longitude":-76.9,"Latitude":18.43,"Status":"Ruin","Classification":"Church"},
    {"Name":"St. Matthew's","Location":"Boscobel","Parish":"St. Mary","Longitude":-77.02,"Latitude":18.41,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Matthew's Church","Location":"Clonmel","Parish":"St. Mary","Longitude":-76.92,"Latitude":18.28,"Status":"Active","Classification":"Church"},
    {"Name":"St. Michael's","Location":"Belfield","Parish":"St. Mary","Longitude":-76.83,"Latitude":18.3,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Patrick's","Location":"Devon Pen","Parish":"St. Mary","Longitude":-76.85,"Latitude":18.2,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Paul's Church (Clarksonville)","Location":"Clarksonville","Parish":"St. Mary","Longitude":-76.89,"Latitude":18.28,"Status":"Ruin","Classification":"Church"},
    {"Name":"St. Peter's","Location":"Galina","Parish":"St. Mary","Longitude":-76.91,"Latitude":18.42,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Peter's Church","Location":"Port Maria","Parish":"St. Mary","Longitude":-76.89,"Latitude":18.37,"Status":"Active","Classification":"Church"},
    {"Name":"St. Simon's Church","Location":"Annotto Bay","Parish":"St. Mary","Longitude":-76.77,"Latitude":18.27,"Status":"Active","Classification":"Church"},
    {"Name":"All Saints'","Location":"The Abbey","Parish":"St. Thomas","Longitude":-76.47,"Latitude":17.97,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"Bath","Location":"Bath","Parish":"St. Thomas","Longitude":-76.35,"Latitude":17.96,"Status":"Unknown","Classification":"Church"},
    {"Name":"Blue Mountain Valley","Location":"Blue Mountain Valley","Parish":"St. Thomas","Longitude":-76.58,"Latitude":18.02,"Status":"Unknown","Classification":"Church"},
    {"Name":"Bull Bay","Location":"Bull Bay","Parish":"St. Thomas","Longitude":-76.67,"Latitude":17.96,"Status":"Unknown","Classification":"Mission Station"},
    {"Name":"Golden Grove","Location":"Golden Grove","Parish":"St. Thomas","Longitude":-76.27,"Latitude":17.92,"Status":"Active","Classification":"Church"},
    {"Name":"Morant Bay","Location":"Morant Bay","Parish":"St. Thomas","Longitude":-76.41,"Latitude":17.88,"Status":"Unknown","Classification":"Church"},
    {"Name":"Mount Felix","Location":"Mount Felix","Parish":"St. Thomas","Longitude":-76.4,"Latitude":17.91,"Status":"Unknown","Classification":"Mission Station"},
    {"Name":"St. Andrew's","Location":"Golden Grove","Parish":"St. Thomas","Longitude":-76.35,"Latitude":17.97,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Augustine's","Location":"Mt. Felix","Parish":"St. Thomas","Longitude":-76.38,"Latitude":17.96,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Barnabas'","Location":"Port Morant","Parish":"St. Thomas","Longitude":-76.39,"Latitude":17.93,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Boniface","Location":"Stony Gut / vicinity","Parish":"St. Thomas","Longitude":-76.36,"Latitude":17.91,"Status":"Unknown","Classification":"Mission Station"},
    {"Name":"St. David's","Location":"Yallahs","Parish":"St. Thomas","Longitude":-76.58,"Latitude":17.89,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. John's","Location":"Woburn Lawn","Parish":"St. Thomas","Longitude":-76.47,"Latitude":17.93,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. John's Church (Old)","Location":"Leith Hall","Parish":"St. Thomas","Longitude":-76.3246,"Latitude":17.8919,"Status":"Ruin","Classification":"Church"},
    {"Name":"St. Paul's","Location":"Danvers Pen","Parish":"St. Thomas","Longitude":-76.42,"Latitude":17.92,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Stephen's","Location":"Thornton","Parish":"St. Thomas","Longitude":-76.37,"Latitude":18.03,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Thomas Parish Church","Location":"Morant Bay","Parish":"St. Thomas","Longitude":-76.41,"Latitude":17.88,"Status":"Active","Classification":"Parish Church"},
    {"Name":"St. Thomas'","Location":"Bath","Parish":"St. Thomas","Longitude":-76.35,"Latitude":17.99,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Thomas' (Parish Church)","Location":"Morant Bay","Parish":"St. Thomas","Longitude":-76.41,"Latitude":17.89,"Status":"Active","Classification":"Parish Church (Church)"},
    {"Name":"Woburn Lawn","Location":"Woburn Lawn","Parish":"St. Thomas","Longitude":-76.33,"Latitude":17.91,"Status":"Unknown","Classification":"Church"},
    {"Name":"Yallahs","Location":"Yallahs","Parish":"St. Thomas","Longitude":-76.56,"Latitude":17.88,"Status":"Unknown","Classification":"Church"},
    {"Name":"St. Andrew's","Location":"Albert Town","Parish":"Trelawny","Longitude":-77.61,"Latitude":18.27,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Barnabas'","Location":"Warsop","Parish":"Trelawny","Longitude":-77.58,"Latitude":18.25,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Mark's","Location":"Rio Bueno","Parish":"Trelawny","Longitude":-77.42,"Latitude":18.47,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Michael's","Location":"Clarks Town","Parish":"Trelawny","Longitude":-77.52,"Latitude":18.32,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Peter's (Parish Church)","Location":"Falmouth","Parish":"Trelawny","Longitude":-77.67,"Latitude":18.49,"Status":"Active","Classification":"Parish Church (Church)"},
    {"Name":"St. Thomas'","Location":"Stewart Town","Parish":"Trelawny","Longitude":-77.48,"Latitude":18.41,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"Holy Trinity","Location":"Grange Hill","Parish":"Westmoreland","Longitude":-78.18074,"Latitude":18.3137,"Status":"Active","Classification":"Church"},
    {"Name":"St. Barnabas'","Location":"George's Plain","Parish":"Westmoreland","Longitude":-78.14349,"Latitude":18.28319,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. George's","Location":"Savanna-la-Mar (Parish Church)","Parish":"Westmoreland","Longitude":-78.14,"Latitude":18.22,"Status":"Active","Classification":"Parish Church (Church)"},
    {"Name":"St. James'","Location":"New Roads (Westmoreland)","Parish":"Westmoreland","Longitude":-77.96,"Latitude":18.19,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. John's","Location":"Darliston","Parish":"Westmoreland","Longitude":-77.97,"Latitude":18.26,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Mary's","Location":"Negril","Parish":"Westmoreland","Longitude":-78.35,"Latitude":18.26,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Matthias'","Location":"Kentucky","Parish":"Westmoreland","Longitude":-78.02,"Latitude":18.24,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Michael's","Location":"Kew Park","Parish":"Westmoreland","Longitude":-78.04,"Latitude":18.27,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Paul's","Location":"Little London","Parish":"Westmoreland","Longitude":-78.25584,"Latitude":18.26234,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Peter's","Location":"Petersfield","Parish":"Westmoreland","Longitude":-78.07,"Latitude":18.29,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"St. Thomas'","Location":"Bluefields","Parish":"Westmoreland","Longitude":-78.01972,"Latitude":18.17144,"Status":"Active","Classification":"Chapel / Church"},
    {"Name":"Transfiguration","Location":"Mount Grace","Parish":"Westmoreland","Longitude":-78.13,"Latitude":18.32,"Status":"Active","Classification":"Chapel / Church"}
];